version: "3"

services:
  database:
    image: "postgres:latest"
    container_name: side-auth
    ports:
      - 5432:5432
    env_file:
      - .env

    volumes:
      - ./data/db-data/:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: side-auth_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./data/pgadmin:/tmp/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
